### ISSUE TITLE
[suggestion] Préciser que l'appli Android n'est pas libre

### ISSUE THREAD

**Issue by tuxayo** [jesuisundesdeux/vigilo-website#30]
Bonjour, sur la page d’accueil on voit «Projet Opensource» ce qui n'est pas le cas [1] pour une partie majeure du projet, à savoir, l'appli Android.

[1] https://github.com/jesuisundesdeux/vigilo-android

**Comment by qhess34** [comment]
Les sources viennent d'être publiées
